name: Jira Action
description: jira action
inputs:
  JIRA_BASE_URL_H:
    description: description
    required: true

runs:
  using: 'docker'
  image: 'golang:alpine'
  entrypoint: ["/bin/sh", "-c"]
  args:
    - 'pwd && ls -l && echo "哈哈哈哈"'