name: Jira Action
description: jira action
inputs:
  JIRA_BASE_URL_H:
    description: description
    required: true

outputs:
  TEST_OUTPUTS:
    description: test
    required: true

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './.github/go.mod'

    - name: Run Go program
      run: |
        echo "Current directory:"
        pwd
        
        go version

        JIRA_URL='url'
        LOGIN='login'
        PASSWORD='pass'
        
        echo "machine $JIRA_URL" > ~/.netrc
        echo "login $LOGIN" >> ~/.netrc
        echo "password $PASSWORD" >> ~/.netrc
        
        cat ~/.netrc
        
        go install github.com/ankitpokhrel/jira-cli/cmd/jira@latest
        go run ./.github/actions/jira/main.go
        
        jira -h
#        jira init

        echo "Generating TEST_OUTPUTS..."
        TEST_OUTPUT="This is a test output"
        echo "::set-output name=TEST_OUTPUTS::$TEST_OUTPUT"

      shell: bash
      env:
        JIRA_URL_H: ${{ inputs.JIRA_BASE_URL_H }}