name: Jira Action
description: jira action
inputs:
  JIRA_BASE_URL:
    description: description
    required: true

runs:
  using: composite
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: './.github/go.mod'

    - name: Run Go program
      run: |
        echo "Current directory:"
        pwd
        echo go version
        go run ./.github/actions/jira/main.go
      shell: bash
      env:
        JIRA_URL: ${{ inputs.JIRA_BASE_URL }}