name: Jira Action
description: jira action
inputs:
  JIRA_BASE_URL:
    description: description
    required: true

runs:
  using: composite
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'

    - name: Run Go program
      run: |
        go run main.go
      env:
        JIRA_URL: ${{ inputs.JIRA_BASE_URL }}