name: Jira Action
description: jira action
inputs:
  JIRA_BASE_URL:
    description: description
    required: true

runs:
  using: 'docker'
  run: |
    go run main.go
  env:
    JIRA_URL: ${{ inputs.JIRA_BASE_URL }}