name: Builder
on:
  pull_request:
    types: [opened, reopened]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: builder
        run: |
          echo 'builder ...'
          sleep 30
          echo 'builder done ...'