name: Builder-Second
on:
  push:
    branches:
      - "**"
  pull_request:
    types: [opened, reopened]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: builder 2
        run: |
          echo 'builder 2 ...'