name: CI with multiple jobs

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run jira action
        uses: ./.github/actions/jira
        with:
          JIRA_BASE_URL: 哈哈