name: CI with multiple jobs

on:
  pull_request:
    types:
      - opened
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run docker
        run: |
          pwd
          ls -al
          docker run --rm \
          -v $GITHUB_WORKSPACE:/workspace \
          -w /workspace \
          golang:latest bash -c "pwd && ls -al"
        shell: bash

      - name: Run jira action
        id: run-jira-action
        uses: ./.github/actions/jira
        with:
          JIRA_BASE_URL_H: 哈哈
