name: Jira
on:
  workflow_run:
    workflows: [Builder, Builder-Second]
    types:
      - completed
jobs:
  jira:
    runs-on: ubuntu-latest
    steps:
      - name: jira
        run: |
          echo 'jira ...'